<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/assets/css/index.css">
    </head>

    <body>
        <div id="nav">
            <a id="button" style="margin-top: 40px; margin-right: 30px;" href="banking">Ingame Banking -></a>
            <a id="button" style="margin-top: 40px; margin-right: 30px;" href="login">Anmelden</a>
            <a id="logoText" href="#">Witzlecraft</a>
        </div>
    </body>

<p>hi gfdgdfgdfgdfg</p>

<style>



</style>

</html>
